name: test

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Yarn Install
        run: yarn install --immutable
      - name: Run Tests
        run: yarn test
